# Generated by Django 5.0.1 on 2024-01-18 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_alter_event_description_alter_event_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='organizations',
            new_name='organizers',
        ),
        migrations.AlterField(
            model_name='organization',
            name='creator',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
