version: '3'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - celery
    volumes:
      - ./:/app

  redis:
    image: "redis:alpine"

  celery:
    build: .
    command: celery -A events_test worker --loglevel=info
    volumes:
      - ./:/app
    depends_on:
      - redis